# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dm-is-published"
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kematzy"]
  s.date = "2013-03-10"
  s.description = "A DataMapper plugin that provides an easy way to add different states to your models."
  s.email = "kematzy@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "dm-is-published.gemspec",
    "docs/apple-touch-icon.png",
    "docs/classes/DataMapper.html",
    "docs/classes/DataMapper/Is.html",
    "docs/classes/DataMapper/Is/Published.html",
    "docs/classes/DataMapper/Is/Published/ClassMethods.html",
    "docs/classes/DataMapper/Is/Published/InstanceMethods.html",
    "docs/classes/DataMapper/Is/Published/ResourceInstanceMethods.html",
    "docs/created.rid",
    "docs/css/github.css",
    "docs/css/main.css",
    "docs/css/panel.css",
    "docs/css/reset.css",
    "docs/favicon.ico",
    "docs/files/README_rdoc.html",
    "docs/files/lib/dm-is-published_rb.html",
    "docs/files/lib/is/published_rb.html",
    "docs/i/arrows.png",
    "docs/i/results_bg.png",
    "docs/i/tree_bg.png",
    "docs/index.html",
    "docs/js/highlight.pack.js",
    "docs/js/jquery-1.3.2.min.js",
    "docs/js/jquery-effect.js",
    "docs/js/main.js",
    "docs/js/navigation.js",
    "docs/js/search_index.js",
    "docs/js/searchdoc.js",
    "docs/js/searcher.js",
    "docs/panel/index.html",
    "docs/panel/links.html",
    "docs/panel/tree.js",
    "lib/dm-is-published.rb",
    "lib/is/published.rb",
    "spec/dm-is-published_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kematzy/dm-is-published"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "A DataMapper plugin that provides an easy way to add different states to your models."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2.7"])
      s.add_runtime_dependency(%q<data_mapper>, ["= 1.2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.12.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12.2"])
      s.add_development_dependency(%q<sdoc>, ["~> 0.3.16"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<dm-mysql-adapter>, ["= 1.2.0"])
      s.add_development_dependency(%q<dm-sqlite-adapter>, ["= 1.2.0"])
      s.add_development_dependency(%q<growl>, [">= 0"])
      s.add_development_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.2.7"])
      s.add_dependency(%q<data_mapper>, ["= 1.2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.12.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12.2"])
      s.add_dependency(%q<sdoc>, ["~> 0.3.16"])
      s.add_dependency(%q<bundler>, ["~> 1.2.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<dm-mysql-adapter>, ["= 1.2.0"])
      s.add_dependency(%q<dm-sqlite-adapter>, ["= 1.2.0"])
      s.add_dependency(%q<growl>, [">= 0"])
      s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.2.7"])
    s.add_dependency(%q<data_mapper>, ["= 1.2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.12.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12.2"])
    s.add_dependency(%q<sdoc>, ["~> 0.3.16"])
    s.add_dependency(%q<bundler>, ["~> 1.2.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<dm-mysql-adapter>, ["= 1.2.0"])
    s.add_dependency(%q<dm-sqlite-adapter>, ["= 1.2.0"])
    s.add_dependency(%q<growl>, [">= 0"])
    s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
  end
end

